apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vcl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: junaid/vcl-www
        ports:
        - containerPort: 80
        - containerPort: 443
      - name: managementnode
        image: junaid/vcl-mgmt
      - name: database
        image: mariadb:10
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: "vcl"
          - name: MYSQL_USER
            value: "vcl"
          - name: MYSQL_PASSWORD
            value: "s3cr3t"
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"